name: ci

on:
  push:
    paths:
      - 'src/**'
    branches:    
      - main
      - 'releases/**'
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
      name: Build and Test
      timeout-minutes: 15
      runs-on: ubuntu-latest
 
      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 20
            registry-url: 'https://registry.npmjs.org'

        - name: Install bun
          uses: oven-sh/setup-bun@v1

        - name: Install dependencies
          run: bun install

        - name: Build
          run: bun run build 

        - name: Typecheck
          run: bun run typecheck

        - name: Test
          run: bun test

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
          env:
             CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

        - name: Release
          id: release
          continue-on-error: true
          if: ${{ success() && (github.event_name != 'pull_request' || github.event.action == 'closed' && github.event.pull_request.merged == true) }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: bun run release

